a = int(input('첫번째 수를 입력하세요: '))
b = int(input('두번쨰 수를 입력하세요: '))
print('-' * 40)
print('a = ',a, ":", bin(a))
print('b = ',b, ":", bin(b))
print('a & b = ', a & b, ":", bin(a &b))
print('a | b = ', a | b, ":", bin(a | b))
print('a ^ b = ', a ^ b, ":", bin(a ^ b))
print('~a = ', ~a,":", bin(~a))