#s1 ='Computer'
#s2 ='Engineering'
#print(s1 +'  ' + s2 + '.')
#print(s2 * 3 )
#print('-' * 20)
#l1 = [1, 2, 3]
#l2 = [4, 5, 6]
#print(l1 + l2)
#print(l1 * 3)

#print('-' * 30)
#print('2 ** 10 = ', 2 ** 10)
#print('5 / 2 = ', 5 / 2)
#print(' 5 // 2 = ', 5 // 2)
#print('5 % 2 = ', 5 % 2)
#print('5 + 2.0 ', 5 + 2.0)
#print('-20 = ', -20)
#print('- -20 = ', - -20)

#print('산술연산자')
#print("-"*20)
#a = int(input('첫번째 정수를 입력하세요: '))
#b = int(input('두번째 정수를 입력하세요: '))
#print('a = ', a)
#print('b = ', b)
#print('a + b = ',a + b)
#print('a - b =',a - b)
#print('a * b = ',a * b)
#print('a / b = ',a / b)
#print('a // b = ',a // b)
#print('a % b = ',a % b)
#print('a ** b = ',a ** b)
#print("-"*20)

#print('산술연산자')
#print("-"*20)
#a = int(input('첫번째 정수를 입력하세요: '))
#b = int(input('두번째 정수를 입력하세요: '))
#print('a = ', a)
#print('b = ', b)
#print("{0} + {1} = {2}".format(a, b, a+b))
#print("{0} - {1} = {2}".format(a, b, a-b))
#print("{0} * {1} = {2}".format(a, b, a*b))
#print("{0} / {1} = {2}".format(a, b, a/b))
#print("{0} // {1} = {2}".format(a, b, a//b))
#print("{0} % {1} = {2}".format(a, b, a%b))
#print("{0} ** {1} = {2}".format(a, b, a**b))
#print("-"*20)

#print('산술연산자')
#print("-"*20)
#a = int(input('첫번째 정수를 입력하세요: '))
#b = float(input('두번째 정수를 입력하세요: '))
#print('a = ', a)
#print('b = ', b)
#print("{0} + {1} = {2}".format(a, b, a+b))
#print("{0} - {1} = {2}".format(a, b, a-b))
#print("{0} * {1} = {2}".format(a, b, a*b))
#print("{0} / {1} = {2}".format(a, b, a/b))
#print("{0} // {1} = {2}".format(a, b, a//b))
#print("{0} % {1} = {2}".format(a, b, a%b))
#print("{0} ** {1} = {2}".format(a, b, a**b))
#print("-"*20)

print(9/2)
print(9/-2)
print(9//-2)
print(9%-2)
print(-9/2)
print(-9//2)
print(-9%2)